### ISSUE TITLE
[pythd] generate dashboard.js.j2 and index.html.j2 for ansible/jinja substitution

### ISSUE THREAD

**Issue by cortadosaxophone** [pyth-network/pyth-client#17]
dashboard.js:
https://github.com/pyth-network/pyth-client/blob/0a614b63e78ef569b5c0e1bf26aef3cd4d9b39be/dashboard/dashboard.js#L128
proposal for dashboard.js.j2:
```javascript
 ws = new WebSocket('ws://{{ ws_host }}:{{ ws_port }}') 
```

index.html:
https://github.com/pyth-network/pyth-client/blob/0a614b63e78ef569b5c0e1bf26aef3cd4d9b39be/dashboard/index.html#L9
proposal for index.html.j2:
```html
 <h2>pyth dashboard {{ dashboard_name }}
```

**Comment by jayantk** [comment]
stale issue; we have dashboards now.
