### ISSUE TITLE
pyth: failed to create key_store directory [13 Permission denied]

### ISSUE THREAD

**Issue by Smea1** [pyth-network/pyth-client#206]
When I'm about to create a solana key pair, it says I don't have permission

I have no name!@116c6ad4bcb5:/home/pyth/pyth-client/build$ ./pyth init_key -k $KDIR
pyth: failed to create key_store directory [13 Permission denied]

**Comment by guibescos** [comment]
Make sure the user that's running this has access to $KDIR and that the $KDIR environment variable is well defined.

**Comment by Smea1** [comment]
> Make sure the user that's running this has access to $KDIR and that the $KDIR environment variable is well defined. Do you have more details?

yes,I want to try uploading prices. According to this link：https://docs.pyth.network/publish-data，but when I want to create a solana account after entering docker and running build.sh, it fails.
This is a screenshot of the command：

I have no name!@38d181fe0c9c:/home/pyth/pyth-client/build$ KDIR=$HOME/.pythd
I have no name!@38d181fe0c9c:/home/pyth/pyth-client/build$ ./pyth init_key -k $KDIR
pyth: failed to create key_store directory [13 Permission denied]

**Comment by Smea1** [comment]
Here is a screenshot of me using the default command

I have no name!@38d181fe0c9c:/home/pyth/pyth-client/build$ ./pythd init_key
pythd: cant find key_store directory [2 No such file or directory]
[2022-07-27T09:12:12.993814Z 413 INF pythd_teardown                          ] secondary=0
