### ISSUE TITLE
pythd: invalid or corrupt product account

### ISSUE THREAD

**Issue by gmarkey** [pyth-network/pyth-client#298]
pyth client (testnet) is crashing with the following error:
```
pythd: invalid or corrupt product account
```

Startup arguments:
```
pythd -r pyth-testnet-rpc-1.solana.p2p.org:80:80 -k /app/pyth-client/keystore -d -w /app/pyth-client/dashboard -x
```

Log file leading up to the crash is attached.
[pyth-client.log.gz](https://github.com/pyth-network/pyth-client/files/9771165/pyth-client.log.gz)

**Comment by tompntn** [comment]
This error occurs because you have configured pythd to use the wrong program/mapping accounts. Note that the accounts are different between testnet and mainnet.
