### ISSUE TITLE
Lack Of Zero Copy Serialization/Deserialization Will Be Problematic For Stack Size

### ISSUE THREAD

**Issue by bonedaddy** [pyth-network/pyth-client#7]
Stack size in solana is fairly limited to 4096bytes, and with the release of pyth v2 price accounts making it difficult to be able to reference price accounts. Zero copy serialization/deserialization would pretty much resolve this issue.

**Comment by richardbrooks2000** [comment]
I don't think its necessary to copy the account data in order to refer to it.

**Comment by mass** [comment]
@bonedaddy could you elaborate a bit on what changes you are envisioning to the price account structure?

**Comment by jayantk** [comment]
no response, closing.
