### ISSUE TITLE
Unable to build v2021-07-27 branch

### ISSUE THREAD

**Issue by rkonda20** [pyth-network/pyth-client#74]
In file included from /home/ubuntu/solana-test/pyth-client/pc/manager.cpp:1:
In file included from /home/ubuntu/solana-test/pyth-client/pc/manager.hpp:5:
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:136:10: error: 'pc::init_mapping::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::create_account * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::create_account *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:137:10: error: 'pc::init_mapping::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::init_mapping * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::init_mapping *')
    void on_response( rpc::program_subscribe * ) override;

/home/ubuntu/solana-test/pyth-client/pc/request.hpp:138:10: error: 'pc::init_mapping::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:195:10: error: 'pc::add_mapping::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::create_account * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::create_account *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:196:10: error: 'pc::add_mapping::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
   void on_response( rpc::add_mapping * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::add_mapping *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:197:10: error: 'pc::add_mapping::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:228:10: error: 'pc::add_product::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::create_account * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::create_account *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:229:10: error: 'pc::add_product::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:230:10: error: 'pc::add_product::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::add_product * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::add_product *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:263:10: error: 'pc::upd_product::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:264:10: error: 'pc::upd_product::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::upd_product * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::upd_product *')
    void on_response( rpc::program_subscribe * ) override;
    /home/ubuntu/solana-test/pyth-client/pc/request.hpp:300:10: error: 'pc::add_price::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::create_account * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::create_account *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:301:10: error: 'pc::add_price::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:302:10: error: 'pc::add_price::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::add_price * ) override;
    /home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::add_price *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:336:10: error: 'pc::init_price::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:337:10: error: 'pc::init_price::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::init_price * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::init_price *')
   void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:367:10: error: 'pc::add_publisher::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::add_publisher * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::add_publisher *')
    void on_response( rpc::program_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:368:10: error: 'pc::add_publisher::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::signature_subscribe * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::signature_subscribe *')
    void on_response( rpc::program_subscribe * ) override;
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:399:10: error: 'pc::del_publisher::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::del_publisher * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::program_subscribe *' vs 'rpc::del_publisher *')
    void on_response( rpc::program_subscribe * ) override;
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/pc.dir/build.make:141: CMakeFiles/pc.dir/pc/manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/pc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by jhunsaker** [comment]
please run `make VERBOSE=1` and paste just the command line which is failing

**Comment by rkonda20** [comment]
/usr/bin/cmake -S/home/ubuntu/solana-test/pyth-client -B/home/ubuntu/solana-test/pyth-client/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/ubuntu/solana-test/pyth-client/build/CMakeFiles /home/ubuntu/solana-test/pyth-client/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/ubuntu/solana-test/pyth-client/build'
make -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/depend
make[2]: Entering directory '/home/ubuntu/solana-test/pyth-client/build'
cd /home/ubuntu/solana-test/pyth-client/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/ubuntu/solana-test/pyth-client /home/ubuntu/solana-test/pyth-client /home/ubuntu/solana-test/pyth-client/build /home/ubuntu/solana-test/pyth-client/build /home/ubuntu/solana-test/pyth-client/build/CMakeFiles/pc.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/ubuntu/solana-test/pyth-client/build'
make -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/build
make[2]: Entering directory '/home/ubuntu/solana-test/pyth-client/build'
[  2%] Building CXX object CMakeFiles/pc.dir/pc/manager.cpp.o
/usr/bin/c++   -I/home/ubuntu/solana-test/pyth-client/build -I/home/ubuntu/solana-test/pyth-client -I/home/ubuntu/solana-test/pyth-client/program/src  -std=c++11 -O3 -DNDEBUG   -ggdb -Wall -Wextra -Werror -m64 -o CMakeFiles/pc.dir/pc/manager.cpp.o -c /home/ubuntu/solana-test/pyth-client/pc/manager.cpp
In file included from /home/ubuntu/solana-test/pyth-client/pc/manager.cpp:1:
In file included from /home/ubuntu/solana-test/pyth-client/pc/manager.hpp:5:
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:159:10: error: 'pc::get_block::on_response' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    void on_response( rpc::get_block * ) override;
         ^
/home/ubuntu/solana-test/pyth-client/pc/request.hpp:102:10: note: hidden overloaded virtual function 'pc::request::on_response' declared here: type mismatch at 1st parameter ('rpc::account_update *' vs 'rpc::get_block *')
    void on_response( rpc::account_update * ) override;
         ^
1 error generated.
make[2]: *** [CMakeFiles/pc.dir/build.make:141: CMakeFiles/pc.dir/pc/manager.cpp.o] Error 1
make[2]: Leaving directory '/home/ubuntu/solana-test/pyth-client/build'
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/pc.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/solana-test/pyth-client/build'
make: *** [Makefile:141: all] Error 2

**Comment by rkonda20** [comment]
I tried main branch too. Same errors

**Comment by jhunsaker** [comment]
can you please send the output of `/usr/bin/c++ --version`?

**Comment by rkonda20** [comment]
ubuntu@ip-172-31-4-38:~$ /usr/bin/c++ --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by rkonda20** [comment]
upgraded my C++ version. That worked. Thanks for the tip. I am all set

Here is my new C++ 
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
